# Struktur Data

## List

In [77]:
aList = ["Yanwar", 19, "Cirebon", True]

In [78]:
aList

['Yanwar', 19, 'Cirebon', True]

In [79]:
type(aList)

list

In [80]:
bin_colors=['Red','Green','Blue','Yellow']

## Tuples

In [81]:
bin_colors=('Red','Green','Blue','Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [82]:
print(f"The element after third element onwards are {bin_colors[2:]}")

The element after third element onwards are ('Blue', 'Yellow')


In [83]:
nested_tuple = (1,2,(100,200,300),0)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


## Dictionary

In [84]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [85]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [86]:
bin_colors.get('approved_color')

'Green'

In [87]:
bin_colors['approved_color']="Purple"

In [88]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


## Set

In [89]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [90]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [91]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'blood', 'rose', 'fire hydrant', 'leaves', 'dandelions'}


In [92]:
print(f"The Interaction of yellow and red is {yellow&red}")

The Interaction of yellow and red is {'fire hydrant', 'leaves'}


## DataFrame

In [93]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Yanwar', 19, True],
    ['2', 'Rizky', 23, False],
    ['3', 'Rendi', 27, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1  Yanwar   19      True
1  2   Rizky   23     False
2  3   Rendi   27      True


### Column Selection

In [94]:
df[['name', 'age']]

name  age
0  Yanwar   19
1   Rizky   23
2   Rendi   27

In [95]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

### Row Selection

In [96]:
df.iloc[1:3,:]

id   name  age  decision
1  2  Rizky   23     False
2  3  Rendi   27      True

In [97]:
df[df.age>25]

id   name  age  decision
2  3  Rendi   27      True

## Matrix

In [98]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

In [99]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [100]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [101]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# Tipe Data Abstrak

## Vector

In [102]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [103]:
print(type(myVector))

<class 'list'>


In [104]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [105]:
print(type(myVector))

<class 'numpy.ndarray'>


## Stack

In [106]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

### Populate the stack

In [107]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

### Pop

In [108]:
stack.pop()

'Yellow'

In [109]:
stack.isEmpty()

False

In [110]:
colors = ['red']

In [111]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [112]:
colors

['red', 'Green', 'Yellow', 'Blue']

## Queue

In [113]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [114]:
queue = Queue()

In [115]:
queue.enqueue('Red')

In [116]:
queue.enqueue('Green')

In [117]:
queue.enqueue('Blue')

In [118]:
queue.enqueue('Yellow')

In [119]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [120]:
print(queue.dequeue())

Red
